name: Ohaasa Instagram Uploader

on:
  schedule:
    # 20분마다 실행 (UTC 기준 20:05 ~ 02:05는 한국 시간 05:05 ~ 11:05)
    - cron: '5/20 20-23 * * 1-5' # 월~금(KST 기준) 오전 05:05~08:59
    - cron: '5/20 0-2 * * 1-5'   # 월~금(KST 기준) 오전 09:05~11:05
  workflow_dispatch: # 수동 실행 버튼 추가

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests Pillow

      - name: Run script
        run: python weekday.py

      - name: Commit success status
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # last_upload.txt가 변경되었다면 커밋하여 중복 실행 방지
          if [ -f last_upload.txt ]; then
            git add last_upload.txt
            git commit -m "Update last upload date" || echo "No changes to commit"
            git push
          fi
